### ISSUE TITLE
Waves node cannot start

### ISSUE THREAD

**Issue by sergelogvinov** [wavesplatform/node-docker-image#6]
The node do not start.
Python script cannot download config file. 

```
# docker run --rm -ti wavesplatform/node

Latest version for TESTNET is:  Version 0.17.2 (Testnet)
Version: latest(0.17.2)
Traceback (most recent call last):
  File "/waves-node/starter.py", line 182, in <module>
    urllib.request.urlretrieve(url, file_path)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Node is starting...
Error: Unable to access jarfile /waves-node/waves-all-latest.jar
```
Github config url has changed.  https://raw.githubusercontent.com/wavesplatform/Waves/v0.17.2/waves-testnet.conf -> https://raw.githubusercontent.com/wavesplatform/Waves/v0.17.2/node/waves-testnet.conf

solution in PR #5

**Comment by KardanovIR** [comment]
Fixed by #5
